export const CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Hyderabad',
  'Gujranwala',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Mardan',
  'Gujrat',
  'Kasur',
]

export const CATEGORIES = [
  { id: 'restaurants', name: 'Restaurants & Food', icon: '🍽️', count: 8420, color: '#f59e0b' },
  { id: 'real-estate', name: 'Real Estate', icon: '🏠', count: 5210, color: '#10b981' },
  { id: 'technology', name: 'Technology & IT', icon: '💻', count: 4890, color: '#60a5fa' },
  { id: 'healthcare', name: 'Healthcare & Medical', icon: '🏥', count: 6320, color: '#ef4444' },
  { id: 'education', name: 'Education & Training', icon: '📚', count: 3780, color: '#8b5cf6' },
  { id: 'retail', name: 'Retail & Shopping', icon: '🛍️', count: 9100, color: '#ec4899' },
  { id: 'construction', name: 'Construction', icon: '🏗️', count: 2340, color: '#f97316' },
  { id: 'automotive', name: 'Automotive', icon: '🚗', count: 3560, color: '#14b8a6' },
  { id: 'finance', name: 'Finance & Banking', icon: '🏦', count: 1890, color: '#6366f1' },
  { id: 'travel', name: 'Travel & Tourism', icon: '✈️', count: 2670, color: '#0ea5e9' },
  { id: 'beauty', name: 'Beauty & Wellness', icon: '💇', count: 4120, color: '#d946ef' },
  { id: 'logistics', name: 'Logistics & Transport', icon: '🚚', count: 1950, color: '#84cc16' },
]
